### ISSUE TITLE
v1.7.0 introduced blade cache issues

### ISSUE THREAD

**Issue by maciek-szn** [blade-ui-kit/blade-icons#248]
### Library version

v1.7.0

### Laravel version

v10.48.18

### PHP version

v8.2.21

### Description

Looks like #245 introduced serious cache issues. After upgrading to v1.7.0 my /storage/framework/views directory is filled with thousands of files that differ only in the value of the `aria-labelledby` attribute, and it's getting worse with every minute. As I understand it, this small difference is due to the fact that the `aria-labelledby` attribute now contains a random value, different every time. This makes it impossible to reuse compiled files - new ones are constantly being generated.

### Steps to reproduce

Just install v1.7.0 and let it go. Check your /storage/framework/views directory after few minutes or hours, depending on how popular your website is.

**Comment by driesvints** [comment]
Most likely happening because of https://github.com/blade-ui-kit/blade-icons/pull/245/files#diff-c17f4a19b6b187c3f1e3c05b299f088d65696dc40479b19d3dc96197f44c05c5R47

@aarishgilani can we maybe change that to something like a hash of the icon name? We'll need to move fast here or I'll have to revert this PR.
